// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoM_eYL3hIOYgbbCcivahXE8CiVdB206A',
    appId: '1:680879674653:web:9390f2448730c6260b3df4',
    messagingSenderId: '680879674653',
    projectId: 'travelreview-app',
    authDomain: 'travelreview-app.firebaseapp.com',
    storageBucket: 'travelreview-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOKYbqUPoMWKjRYG8zEEtMw5L-J9Bd_OU',
    appId: '1:680879674653:android:42ff3b8d55f18d7b0b3df4',
    messagingSenderId: '680879674653',
    projectId: 'travelreview-app',
    storageBucket: 'travelreview-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAziZ-YOFZi9F_ByI_QHS35tjI7zKtTWzw',
    appId: '1:680879674653:ios:04af4e1723d31a100b3df4',
    messagingSenderId: '680879674653',
    projectId: 'travelreview-app',
    storageBucket: 'travelreview-app.firebasestorage.app',
    iosBundleId: 'com.travelreview.travelreviewApp',
  );
}
